plugins {
    id 'java'
    id 'io.qameta.allure' version '4.1.0'
}

group = 'org.upiresti'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Cucumber
    testImplementation 'io.cucumber:cucumber-java:7.18.1'
    testImplementation 'io.cucumber:cucumber-junit-platform-engine:7.18.1'

    // Selenium
    testImplementation 'org.seleniumhq.selenium:selenium-java:4.25.0'

    // JUnit 5
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.0'
    testImplementation 'org.junit.platform:junit-platform-suite:1.11.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // REST Assured
    testImplementation 'io.rest-assured:rest-assured:5.5.0'

    // Allure
    testImplementation platform('io.qameta.allure:allure-bom:2.35.3')
    testImplementation 'io.qameta.allure:allure-cucumber7-jvm'
}

allure {
    version = '2.36.0'

    adapter {
        aspectjWeaver.set(false)
        frameworks {
            cucumber7Jvm
        }
    }
}

test {
    useJUnitPlatform()

    testLogging {
        showStandardStreams = true
        events "passed", "skipped", "failed"
    }
}

tasks.register('apiTest', Test) {
    description = 'Execute Cucumber tests with @api tag'
    group = 'verification'

    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath

    useJUnitPlatform()

    filter {
        includeTestsMatching 'org.upiresti.ApiTestRunner'
    }
}

tasks.register('webTest', Test) {
    description = 'Execute Cucumber tests with @web tag'
    group = 'verification'

    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath

    useJUnitPlatform()

    filter {
        includeTestsMatching 'org.upiresti.WebTestRunner'
    }
}

webTest.mustRunAfter(apiTest)

tasks.register('automationTest') {
    description = 'Execute API and Web automation tests'
    group = 'verification'

    dependsOn apiTest, webTest
}

tasks.named('allureReport') {
    dependsOn automationTest
}